# Generated by Django 6.0.1 on 2026-01-29 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.FloatField()),
                ('product_category', models.CharField(choices=[(1, 'Iphone'), (2, 'Macbook'), (3, 'Ipad'), (4, 'Accessories')], max_length=50)),
                ('product_description', models.TextField()),
                ('is_available', models.BooleanField(default=True)),
                ('product_image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
