# Generated by Django 6.0.1 on 2026-01-30 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_category',
            field=models.IntegerField(choices=[(1, 'Iphone'), (2, 'Macbook'), (3, 'Ipad'), (4, 'Accessories')], default=1),
        ),
    ]
