# Generated by Django 6.0.1 on 2026-01-31 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_products_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_category',
            field=models.IntegerField(choices=[(1, 'Iphone'), (2, 'Macbook'), (3, 'Ipad'), (4, 'Watch'), (5, 'AirPods'), (6, 'TV & Home'), (7, 'Entertainment')], default=1),
        ),
    ]
