# Generated by Django 6.0.1 on 2026-02-05 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='confirm_password',
        ),
    ]
