# Generated by Django 6.0.1 on 2026-02-12 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_users_confirm_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
